# Generated by Django 4.0.2 on 2022-02-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, verbose_name='Category User Friendly Name')),
                ('description', models.TextField(verbose_name='Category Description')),
                ('thumbnail', models.ImageField(upload_to='categories', verbose_name='Category Thumbanil')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('path', models.ImageField(upload_to='products', verbose_name='Image')),
                ('alt_text', models.CharField(max_length=100, verbose_name='Media Alt Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(choices=[('ge', 'general'), ('co', 'colors'), ('qu', 'quantity')], max_length=3, verbose_name='Option Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('slug', models.SlugField(blank=True, verbose_name='Tag User Friendly Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=75, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Product Featured?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.category', verbose_name='Product Category')),
                ('tags', models.ManyToManyField(related_name='product_tags', to='store.Tag', verbose_name='Product Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Option Value Name')),
                ('price', models.IntegerField(verbose_name='Option Value Price')),
                ('purchase_price', models.IntegerField(verbose_name='Option Value Purchase Price')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Is Discount?')),
                ('discount_price', models.IntegerField(verbose_name='Option Value Discount Price')),
                ('sku', models.CharField(max_length=10, verbose_name='Option Value SKU Code')),
                ('in_stock', models.IntegerField(verbose_name='Option Value In Stock')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is Option Main?')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='store.option', verbose_name='Option Value Parent Option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product', verbose_name='Option Value Product')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='store.image', verbose_name='Option Value Thumbnail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
