# Generated by Django 4.0.2 on 2022-04-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='store.product', verbose_name='Option Value Product'),
        ),
    ]
