# Generated by Django 4.0.2 on 2022-04-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_optionvalue_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'ordering': ['-is_main']},
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(default='Code', max_length=50, verbose_name='Option Value for Colors'),
        ),
    ]
