# Generated by Django 4.0.2 on 2022-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_optionvalue_options_optionvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvalue',
            name='is_set',
            field=models.BooleanField(default=False, verbose_name='Is set?'),
        ),
    ]
